name: Netlify

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: nelonoel/branch-name@v1.0.1

      - name: Publish preview
        uses: jsmrcaga/action-netlify-deploy@v2.4.0
        if: env.NETLIFY_AUTH_TOKEN
        with:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ env.NETLIFY_AUTH_TOKEN }}
          NETLIFY_DEPLOY_MESSAGE: Preview ${{ env.BRANCH_NAME }}
          build_directory: packages/demo/dist
          monorepo_package: shape-to-query
          deploy_alias: ${{ env.BRANCH_NAME }}
          NETLIFY_DEPLOY_TO_PROD: ${{ env.BRANCH_NAME == 'master' }}

      - uses: exercism/pr-commenter-action@v1.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          template-variables: |
            {
              "url": "${{ env.NETLIFY_PREVIEW_URL }}"
            }
