name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 20, "lts/-2", "lts/-1", "lts/*" ]
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test
      - name: Codecov (unit tests)
        uses: codecov/codecov-action@v5
        with:
          files: coverage/unit/lcov.info
          flags: unit-tests
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Codecov (query tests)
        uses: codecov/codecov-action@v5
        with:
          files: coverage/query/lcov.info
          flags: sparql-tests
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
      - run: npm ci
      - run: npx tsc --noEmit

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run lint

  no-circular:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
      - run: npm ci
      - run: npx tsc
      - run: npx madge --circular packages/shape-to-query/index.js
